"""empty message

Revision ID: b8447c4ed4c8
Revises: fd4a3bc7fa71
Create Date: 2024-03-21 00:24:11.625109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8447c4ed4c8'
down_revision = 'fd4a3bc7fa71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('albuns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('albuns', schema=None) as batch_op:
        batch_op.drop_column('foto')

    # ### end Alembic commands ###
